name: cookie_client
description: The Http Client package that depends on the dio package.
version: 0.1.0+1


environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: 3.3.10

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ">=0.3.0 <2.0.0"
  flutter_lints: ^2.0.0
